# Generated by Django 4.2.2 on 2023-07-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
