# Generated by Django 4.2.2 on 2023-08-17 14:10

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleveryManInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('national_id', models.CharField(max_length=50)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to=accounts.utils.user_directory_path)),
                ('signature', models.ImageField(upload_to=accounts.utils.user_directory_path)),
                ('info_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
