# Generated by Django 4.2.2 on 2023-08-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deleveryman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleverymaninfo',
            name='info_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deleveryman_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
