# Generated by Django 4.2.2 on 2023-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deleveryman', '0002_alter_deleverymaninfo_info_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleverymaninfo',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='deleverymaninfo',
            name='signature',
            field=models.ImageField(upload_to=''),
        ),
    ]
