# Generated by Django 4.2.2 on 2023-07-28 06:40

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='sale_price',
            field=models.FloatField(blank=True, default=None, null=True, validators=[common.validators.validate_float_value]),
        ),
    ]
