# Generated by Django 4.2.2 on 2023-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productbatch_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('featured', 'Featured'), ('general', 'General')], default='general', max_length=15),
        ),
    ]
